
logging:
  log_dir: "C:\\Logs"
patterns:
  redacting_patterns:
    EMAIL: '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
    PHONE: '\b(\+?\d{1,2})?\s?(\(?\d{3}\)?)?\s?-?\d{3}-?\d{4}\b'
    SSN: '\b\d{3}-\d{2}-\d{4}\b'
    CREDIT_CARD: '\b(?:\d{4}-?){3}\d{4}\b'
    DATE_OF_BIRTH: '\b\d{2}[/-]\d{2}[/-]\d{4}\b'
    PASSPORT: '\b[0-9]{9}\b'  # Example for U.S. passport numbers
    DRIVER_LICENSE: '\b[A-Z]{1,2}-\d{3,6}-\d{3,6}\b'
    BANK_ACCOUNT: '\b\d{9,18}\b'
    IP_ADDRESS: '\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b'
    MAC_ADDRESS: '\b([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})\b'
    PHYSICAL_ADDRESS: '\b\d+\s[A-Za-z]+(?:\s[A-Za-z]+)*\b'  # Basic pattern